version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: livewire/livewire
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
  - dependency-name: symfony/http-kernel
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: spatie/laravel-permission
    versions:
    - 3.18.0
    - 4.0.0
  - dependency-name: nunomaduro/collision
    versions:
    - 5.3.0
  - dependency-name: laravel/framework
    versions:
    - 7.30.3
  - dependency-name: langleyfoxall/laravel-nist-password-rules
    versions:
    - 4.4.1
  - dependency-name: barryvdh/laravel-debugbar
    versions:
    - 3.5.2
  - dependency-name: mockery/mockery
    versions:
    - 1.4.2
